### ISSUE TITLE
[marathon_reporter] Republishing Session Mileage and Duration

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_apps#23]
Hi @cburbridge, 

Do you think it will be fine to republish `self._current_session.distance` and `self._current_session.duration` as topics, so for example our tweeting node can use this info?

**Comment by cburbridge** [comment]
Sure I'll add that shortly. self._current_session is a ROS message itself
(marathon_reporter/MarathonSession) so I could just publish that. However,
then you need to depend on marathon_reporter.  Alternatively I could make
two topics using std_msgs/Float32 and std_msgs/Duration message types. What
would you prefer?

I think I prefer the single topic since a marathon tweeter probably depends
on a marathon reporter. In fact, the tweeter could be in the same package?

**Comment by marc-hanheide** [comment]
:+1: for it being the same package, if it's marathon specific
